-- SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
-- FROM REST_INFO
-- WHERE FAVORITES IN (
-- 	SELECT MAX(FAVORITES)
--     FROM REST_INFO
-- 	GROUP BY FOOD_TYPE
-- )
-- GROUP BY FOOD_TYPE
-- ORDER BY FOOD_TYPE DESC;

WITH A AS (
	SELECT FOOD_TYPE, MAX(FAVORITES) AS MAXFAV
	FROM REST_INFO
	GROUP BY FOOD_TYPE
)
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R, A
WHERE R.FOOD_TYPE = A.FOOD_TYPE AND R.FAVORITES = A.MAXFAV
ORDER BY FOOD_TYPE DESC;