WITH PARENT AS (
    SELECT t.PARENT_ITEM_ID, i.RARITY, t.ITEM_ID
    FROM ITEM_TREE t
    JOIN ITEM_INFO i ON t.PARENT_ITEM_ID = i.ITEM_ID
    WHERE i.RARITY = 'RARE'
)
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM PARENT p
JOIN ITEM_INFO i ON p.ITEM_ID = i.ITEM_ID
ORDER BY ITEM_ID DESC;